version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16  # Define la versión de Node.js
    commands:
      - echo "Installing dependencies..."
      - npm install  # Instala las dependencias

  build:
    commands:
      - echo "Building the React app..."
      - npm run build  # Construye el proyecto de React para producción


artifacts:
  files:
    - '**/*'  # Incluye todos los archivos generados
  base-directory: build  # Define que la base para los archivos es la subcarpeta build
